### ISSUE TITLE
Possible to add a license?

### ISSUE THREAD

**Issue by jonathan-optimusride** [goenning/ts-selenium#5]
Hello,

I would love to use your project as a starter template for a professional project I'm working on building a Selenium test suite to execute browser tests written in TypeScript. At my company however we have a strict policy against using unlicensed code.

Is there any way you could add a business friendly license such as MIT, Apache 2.0, or one of the BSD licenses to your project? My assumption is that you published the example to help fellow programmers build upon your work, adding such a license would facilitate that in professional environments.

Github makes it pretty easy to do this, and here are some resources to help choose.
https://choosealicense.com/
https://help.github.com/articles/licensing-a-repository/

Much appreciated

**Comment by goenning** [comment]
Done! :)

**Comment by jonathan-optimusride** [comment]
Thanks!
